/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import control.ControlEmpleado;

/**
 *
 * @author jalt2
 */
public class MenuJefe extends javax.swing.JFrame {
    private ControlEmpleado control;
    /**
     * Creates new form MenuJefe
     */
    public MenuJefe(ControlEmpleado control) {
        initComponents();
        this.control=control;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuAdministracion = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        administrarSubordinado = new javax.swing.JMenu();
        agregarSubordinado = new javax.swing.JMenuItem();
        eliminarSubordinado = new javax.swing.JMenuItem();
        administrarEmpleados = new javax.swing.JMenu();
        registrarEmpleado = new javax.swing.JMenuItem();
        eliminarEmpleado = new javax.swing.JMenuItem();
        modificarEmpleado = new javax.swing.JMenuItem();
        mostrarEmpleados = new javax.swing.JMenuItem();
        menuPrestamo = new javax.swing.JMenu();
        realizarPrestamo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Bienvenido!");

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Cerrar Sesion");

        menuAdministracion.setText("Administracion");
        menuAdministracion.add(jSeparator1);

        administrarSubordinado.setText("Administrar Subordinados");

        agregarSubordinado.setText("Agregar Subordinado");
        agregarSubordinado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarSubordinadoActionPerformed(evt);
            }
        });
        administrarSubordinado.add(agregarSubordinado);

        eliminarSubordinado.setText("Eliminar Subordinado");
        eliminarSubordinado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarSubordinadoActionPerformed(evt);
            }
        });
        administrarSubordinado.add(eliminarSubordinado);

        menuAdministracion.add(administrarSubordinado);

        administrarEmpleados.setText("Administrar Empleados");

        registrarEmpleado.setText("Registrar Empleado");
        registrarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarEmpleadoActionPerformed(evt);
            }
        });
        administrarEmpleados.add(registrarEmpleado);

        eliminarEmpleado.setText("Eliminar Empleado");
        eliminarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarEmpleadoActionPerformed(evt);
            }
        });
        administrarEmpleados.add(eliminarEmpleado);

        modificarEmpleado.setText("Modificar Empleado");
        modificarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarEmpleadoActionPerformed(evt);
            }
        });
        administrarEmpleados.add(modificarEmpleado);

        mostrarEmpleados.setText("Mostrar Empleados");
        mostrarEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarEmpleadosActionPerformed(evt);
            }
        });
        administrarEmpleados.add(mostrarEmpleados);

        menuAdministracion.add(administrarEmpleados);

        jMenuBar1.add(menuAdministracion);

        menuPrestamo.setText("Prestamos");

        realizarPrestamo.setText("Realizar Prestamo");
        menuPrestamo.add(realizarPrestamo);

        jMenuBar1.add(menuPrestamo);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addComponent(jLabel1)
                .addContainerGap(224, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarSubordinadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarSubordinadoActionPerformed
        // TODO add your handling code here:
        control.iniciarAgregarSubordinado();
    }//GEN-LAST:event_agregarSubordinadoActionPerformed

    private void eliminarSubordinadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarSubordinadoActionPerformed
        // TODO add your handling code here:
        control.iniciarEliminarSubordinado();
    }//GEN-LAST:event_eliminarSubordinadoActionPerformed

    private void mostrarEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarEmpleadosActionPerformed
        // TODO add your handling code here:
        control.iniciarfrmMostrarEmpleados();
    }//GEN-LAST:event_mostrarEmpleadosActionPerformed

    private void registrarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarEmpleadoActionPerformed
        // TODO add your handling code here:
        control.iniciarAgregarEmpleado();
    }//GEN-LAST:event_registrarEmpleadoActionPerformed

    private void eliminarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarEmpleadoActionPerformed
        // TODO add your handling code here:
        control.iniciarEliminarEmpleado();
        
    }//GEN-LAST:event_eliminarEmpleadoActionPerformed

    private void modificarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarEmpleadoActionPerformed
        // TODO add your handling code here:
        this.control.iniciarModificarEmpleado();
    }//GEN-LAST:event_modificarEmpleadoActionPerformed

        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu administrarEmpleados;
    private javax.swing.JMenu administrarSubordinado;
    private javax.swing.JMenuItem agregarSubordinado;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JMenuItem eliminarEmpleado;
    private javax.swing.JMenuItem eliminarSubordinado;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenu menuAdministracion;
    private javax.swing.JMenu menuPrestamo;
    private javax.swing.JMenuItem modificarEmpleado;
    private javax.swing.JMenuItem mostrarEmpleados;
    private javax.swing.JMenuItem realizarPrestamo;
    private javax.swing.JMenuItem registrarEmpleado;
    // End of variables declaration//GEN-END:variables
}
