/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import control.ControlEmpleado;

/**
 *
 * @author jalt2
 */
public class MenuJefe extends javax.swing.JFrame {
    private ControlEmpleado control;
    /**
     * Creates new form MenuJefe
     */
    public MenuJefe(ControlEmpleado control) {
        initComponents();
        this.control=control;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuAdministracion = new javax.swing.JMenu();
        administrarSubordinado = new javax.swing.JMenuItem();
        administrarEmpleado = new javax.swing.JMenuItem();
        administrarPrestamos = new javax.swing.JMenuItem();
        menuPrestamo = new javax.swing.JMenu();
        realizarPrestamo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Bienvenido!");

        menuAdministracion.setText("Administracion");

        administrarSubordinado.setText("Administrar Subordinados");
        administrarSubordinado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                administrarSubordinadoActionPerformed(evt);
            }
        });
        menuAdministracion.add(administrarSubordinado);

        administrarEmpleado.setText("Administrar Empleados");
        administrarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                administrarEmpleadoActionPerformed(evt);
            }
        });
        menuAdministracion.add(administrarEmpleado);

        administrarPrestamos.setText("Administrar Prestamos");
        administrarPrestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                administrarPrestamosActionPerformed(evt);
            }
        });
        menuAdministracion.add(administrarPrestamos);

        jMenuBar1.add(menuAdministracion);

        menuPrestamo.setText("Prestamos");

        realizarPrestamo.setText("Realizar Prestamo");
        menuPrestamo.add(realizarPrestamo);

        jMenuBar1.add(menuPrestamo);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addComponent(jLabel1)
                .addContainerGap(224, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jLabel1)
                .addContainerGap(176, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void administrarSubordinadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_administrarSubordinadoActionPerformed
        // TODO add your handling code here:
        control.iniciarFrmSubordinados();
        this.dispose();
    }//GEN-LAST:event_administrarSubordinadoActionPerformed

    private void administrarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_administrarEmpleadoActionPerformed
        // TODO add your handling code here:
        control.iniciarFrmEmpleados();
    }//GEN-LAST:event_administrarEmpleadoActionPerformed

    private void administrarPrestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_administrarPrestamosActionPerformed
        // TODO add your handling code here:
        control.iniciarFrmPrestamos();
    }//GEN-LAST:event_administrarPrestamosActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem administrarEmpleado;
    private javax.swing.JMenuItem administrarPrestamos;
    private javax.swing.JMenuItem administrarSubordinado;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuAdministracion;
    private javax.swing.JMenu menuPrestamo;
    private javax.swing.JMenuItem realizarPrestamo;
    // End of variables declaration//GEN-END:variables
}
